---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/psllogco/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp ar.html $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
